name = "cloudflare-docker-proxy"
type = "webpack"

account_id = ""
workers_dev = true
route = ""
zone_id = ""

webpack_config = "webpack.config.js"
compatibility_date = "2021-12-07"


[dev]
ip = "0.0.0.0"
port = 8787
local_protocol="http"
upstream_protocol="https"

[vars]
MODE="production"
LOCAL_ADDRESS=""
TARGET_UPSTREAM=""

[env.dev.vars]
MODE="debug"
LOCAL_ADDRESS="http://192.168.50.160:8787"
TARGET_UPSTREAM="https://registry-1.docker.io"